/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as SongsImport } from './routes/songs';
import { Route as IndexImport } from './routes/index';
import { Route as SongIdImport } from './routes/song/$id';

// Create/Update Routes

const SongsRoute = SongsImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const SongIdRoute = SongIdImport.update({
  id: '/song/$id',
  path: '/song/$id',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/songs': {
      id: '/songs';
      path: '/songs';
      fullPath: '/songs';
      preLoaderRoute: typeof SongsImport;
      parentRoute: typeof rootRoute;
    };
    '/song/$id': {
      id: '/song/$id';
      path: '/song/$id';
      fullPath: '/song/$id';
      preLoaderRoute: typeof SongIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/songs': typeof SongsRoute;
  '/song/$id': typeof SongIdRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/songs': typeof SongsRoute;
  '/song/$id': typeof SongIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/songs': typeof SongsRoute;
  '/song/$id': typeof SongIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/songs' | '/song/$id';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/songs' | '/song/$id';
  id: '__root__' | '/' | '/songs' | '/song/$id';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SongsRoute: typeof SongsRoute;
  SongIdRoute: typeof SongIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SongsRoute: SongsRoute,
  SongIdRoute: SongIdRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/songs",
        "/song/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/songs": {
      "filePath": "songs.tsx"
    },
    "/song/$id": {
      "filePath": "song/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
