volumes:
  moises-ai.api:
    external: true # NOTE: only useful if we want another docker instance to connect to the volume for schema migrations

services:
  postgres:
    image: postgres:14-alpine
    env_file: api.env
    ports:
      - 5432:5432
    volumes:
      - moises-ai.api:/var/lib/postgresql/data
